"""
AgentState — the shared state dictionary for the LangGraph StateGraph.

Every node in the graph reads from and writes back to this TypedDict.
Think of it as the "conveyor belt" that carries data through the pipeline.
"""

import operator
from typing import Annotated, Optional, Union
from typing_extensions import TypedDict
from langchain_core.messages import AnyMessage
from langgraph.graph.message import add_messages


class AgentState(TypedDict):
    # --- Input & History ---
    user_message: str
    # Standard LangGraph conversation history (add_messages merges lists)
    messages: Annotated[list[AnyMessage], add_messages]
    # Formatted recent conversation turns (text string for prompts)
    memory_context: Optional[str]

    # --- Routing ---
    # The chosen route: 'direct', 'sql_generator', 'result_interpreter'
    route: Optional[str]
    # One concise sentence explaining the routing decision
    reasoning: Optional[str]

    # --- Tool & Execution ---
    # The generated SQL query (if any)
    sql_generated: Optional[str]
    # Raw query results from the database (list of dicts)
    result: Optional[Union[list, dict, str]]
    
    # --- Final Output ---
    # The human-readable response generated by the synthesizer or direct agent
    final_answer: Optional[str]

    # --- Metadata & Flow Control ---
    user_id: Optional[str]
    session_id: Optional[str]
    # Captured error message if any step fails
    error: Optional[str]
